version: "3"
services:
  strapi:
    build:
      context: ./app
    restart: unless-stopped
    ports:
      - "1337:1337"
      # - "1333-1337:1337"  // les ports pour plusieurs instances 
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - ./app:/opt/app
    depends_on:
      - postgres
    # deploy:
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 2G
      #   reservations:
      #     memory: 512M
      # replicas: 5
    networks:
      - mynetwork

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: quangminh1575@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - mynetwork

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  pgadmin-data:
  local_pgdata:

networks:
  mynetwork:
